import pickle
import os

max_realizations = 15
fhd_runs_medium_noise_01_m = 1.03
fhd_runs_medium_noise_015_m = 1.53
fhd_runs_medium_noise_05_m = 3.46
fhd_runs_medium_noise_1_m = 5.12

many_sigma_combos = [
            # only thermal noise (max realizations)
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10,
                "sigma_n": 10, 
                "sigma_m": 1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 10, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 10, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 10, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 0.1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10,
                "sigma_n": 10, 
                "sigma_m": 0.1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 0.1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            # thermal noise (max realizations) and model error (1 realization)
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            # thermal noise (max realizations) and model error (max realizations)
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            # thermal noise (1 realization) and model error (max realizations)
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10,
                "sigma_n": 10, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            # only model noise (100 realizations)
            {
                "sigma_t": 1, 
                "sigma_n": 0, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 0, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 0, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 0, 
                "sigma_m": 1, 
                "sigma_e": 1,
                "thermal_noise_realizations": 1,
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 0, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 0, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
        ]

with open('calico/data/original_many_realizations.pkl', 'wb') as file:
    pickle.dump(many_sigma_combos, file)

baseline_dependence_runs_large_noise = [
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "step_down_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 0.1,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 10,
            },
        ]

baseline_dependence_runs_small_noise = [
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "step_down_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 0.1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 200,
            },
        ]

add_gaussian_error_medium_noise = [
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 10,
            },
        ]

add_gaussian_error_small_noise = [
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_medium_noise_01 = [
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_medium_noise_015 = [
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_medium_noise_05 = [
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_medium_noise_1 = [
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_small_noise_01 = [
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_small_noise_015 = [
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_small_noise_05 = [
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_small_noise_1 = [
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_large_noise_01 = [
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_large_noise_015 = [
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_large_noise_05 = [
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_large_noise_1 = [
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

def generate_files():
    cwd = os.getcwd()
    with open(f'{cwd}/calico/data/sigma_combos_many_realizations.pkl', 'wb') as file:
        pickle.dump(many_sigma_combos, file)
    with open(f'{cwd}/calico/data/baseline_dependence_runs_large_noise.pkl', 'wb') as file:
        pickle.dump(baseline_dependence_runs_large_noise, file)
    with open(f'{cwd}/calico/data/baseline_dependence_runs_small_noise.pkl', 'wb') as file:
        pickle.dump(baseline_dependence_runs_small_noise, file)
    with open(f'{cwd}/calico/data/add_gaussian_error_large_noise.pkl', 'wb') as file:
        pickle.dump(add_gaussian_error_medium_noise, file)
    with open(f'{cwd}/calico/data/add_gaussian_error_small_noise.pkl', 'wb') as file:
        pickle.dump(add_gaussian_error_small_noise, file)
    with open(f'{cwd}/calico/data/fhd_runs_medium_noise_01.pkl', 'wb') as file:
        pickle.dump(fhd_runs_medium_noise_01, file)
    with open(f'{cwd}/calico/data/fhd_runs_medium_noise_015.pkl', 'wb') as file:
        pickle.dump(fhd_runs_medium_noise_015, file)
    with open(f'{cwd}/calico/data/fhd_runs_medium_noise_05.pkl', 'wb') as file:
        pickle.dump(fhd_runs_medium_noise_05, file)
    with open(f'{cwd}/calico/data/fhd_runs_medium_noise_1.pkl', 'wb') as file:
        pickle.dump(fhd_runs_medium_noise_1, file)
    with open(f'{cwd}/calico/data/fhd_runs_small_noise_01.pkl', 'wb') as file:
        pickle.dump(fhd_runs_small_noise_01, file)
    with open(f'{cwd}/calico/data/fhd_runs_small_noise_015.pkl', 'wb') as file:
        pickle.dump(fhd_runs_small_noise_015, file)
    with open(f'{cwd}/calico/data/fhd_runs_small_noise_05.pkl', 'wb') as file:
        pickle.dump(fhd_runs_small_noise_05, file)
    with open(f'{cwd}/calico/data/fhd_runs_small_noise_1.pkl', 'wb') as file:
        pickle.dump(fhd_runs_small_noise_1, file)
    with open(f'{cwd}/calico/data/fhd_runs_large_noise_01.pkl', 'wb') as file:
        pickle.dump(fhd_runs_large_noise_01, file)
    with open(f'{cwd}/calico/data/fhd_runs_large_noise_015.pkl', 'wb') as file:
        pickle.dump(fhd_runs_large_noise_015, file)
    with open(f'{cwd}/calico/data/fhd_runs_large_noise_05.pkl', 'wb') as file:
        pickle.dump(fhd_runs_large_noise_05, file)
    with open(f'{cwd}/calico/data/fhd_runs_large_noise_1.pkl', 'wb') as file:
        pickle.dump(fhd_runs_large_noise_1, file)

generate_files()