import pickle
import os

import hickle as hkl

max_realizations = 1
fhd_runs_medium_noise_01_m = 1.03
fhd_runs_medium_noise_015_m = 1.53
fhd_runs_medium_noise_05_m = 3.46
fhd_runs_medium_noise_1_m = 5.12

many_sigma_combos = [
            # only thermal noise (max realizations)
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10,
                "sigma_n": 10, 
                "sigma_m": 1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 10, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 10, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 10, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 0.1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10,
                "sigma_n": 10, 
                "sigma_m": 0.1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 0.1, 
                "sigma_e": 0, 
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            # thermal noise (max realizations) and model error (1 realization)
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            # thermal noise (max realizations) and model error (max realizations)
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": max_realizations, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            # thermal noise (1 realization) and model error (max realizations)
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0.1, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10,
                "sigma_n": 10, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 10, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            # only model noise (100 realizations)
            {
                "sigma_t": 1, 
                "sigma_n": 0, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 0, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1, 
                "sigma_n": 0, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 0, 
                "sigma_m": 1, 
                "sigma_e": 1,
                "thermal_noise_realizations": 1,
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 0, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 10, 
                "sigma_n": 0, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0, 
                "sigma_m": 1, 
                "sigma_e": 1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1, 
                "sigma_n": 0, 
                "sigma_m": 10, 
                "sigma_e": 10, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0, 
                "sigma_m": 0.1, 
                "sigma_e": 0.1, 
                "thermal_noise_realizations": 1, 
                "model_error_realizations": max_realizations,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 1,
                "scaling_factor_cost": 1,
            },
        ]

# with open('calico/data/original_many_realizations.hkl', mode='wb') as file:
hkl.dump(many_sigma_combos, 'calico/data/original_many_realizations.hkl', compression='gzip')

baseline_dependence_runs_large_noise = [
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "step_down_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 0.1,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": 1,
                "sigma_n": 1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 10,
            },
        ]

baseline_dependence_runs_small_noise = [
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "step_down_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 0.1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 1,
                "sigma_e": 1,
                # "sigma_e": 0,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 200,
            },
        ]

add_gaussian_error_medium_noise = [
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 0.1,
                "sigma_e": 0.1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1,
            },
            # {
            #     "sigma_t": 1,
            #     "sigma_n": 1,
            #     "sigma_m": 1,
            #     "sigma_e": 1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 1.2,
            # },
            # {
            #     "sigma_t": 1,
            #     "sigma_n": 1,
            #     "sigma_m": 1,
            #     "sigma_e": 1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 2,
            # },
            # {
            #     "sigma_t": 1,
            #     "sigma_n": 1,
            #     "sigma_m": 1,
            #     "sigma_e": 1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 5,
            # },
            # {
            #     "sigma_t": 1,
            #     "sigma_n": 1,
            #     "sigma_m": 1,
            #     "sigma_e": 1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 10,
            # },
            {
                "sigma_t": 0.1,
                "sigma_n": 0.1,
                "sigma_m": 0.1,
                "sigma_e": 0.1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 200,
            },
        ]

add_gaussian_error_small_noise = [
            {
                "sigma_t": 0.01,
                "sigma_n": 0.01,
                "sigma_m": 9,
                "sigma_e": 9,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1,
            },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 0.1,
            #     "sigma_e": 0.1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 1.2,
            # },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 0.1,
            #     "sigma_e": 0.1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 2,
            # },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 0.1,
            #     "sigma_e": 0.1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 5,
            # },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 0.1,
            #     "sigma_e": 0.1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 10,
            # },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 0.1,
            #     "sigma_e": 0.1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 100,
            # },
            {
                "sigma_t": 0.01,
                "sigma_n": 0.01,
                "sigma_m": 9,
                "sigma_e": 9,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 200,
            },
        ]

add_gaussian_error_large_noise = [
            {
                "sigma_t": 0.12,
                "sigma_n": 0.12,
                "sigma_m": 0.1,
                "sigma_e": 0.1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 1,
            },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 1,
            #     "sigma_e": 1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 1.2,
            # },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 1,
            #     "sigma_e": 1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 2,
            # },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 1,
            #     "sigma_e": 1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 5,
            # },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 1,
            #     "sigma_e": 1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 10,
            # },
            # {
            #     "sigma_t": 0.1,
            #     "sigma_n": 0.1,
            #     "sigma_m": 1,
            #     "sigma_e": 1,
            #     "thermal_noise_realizations": max_realizations,
            #     "model_error_realizations": 1,
            #     "weighting_function": "constant_weights",
            #     "scaling_factor_sim": 0.1,
            #     "scaling_factor_cost": 100,
            # },
            {
                "sigma_t": 0.12,
                "sigma_n": 0.12,
                "sigma_m": 0.1,
                "sigma_e": 0.1,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 1,
                "weighting_function": "constant_weights",
                "scaling_factor_sim": 0.1,
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_medium_noise_01 = [
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m,
                "sigma_n": fhd_runs_medium_noise_01_m,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_medium_noise_015 = [
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m,
                "sigma_n": fhd_runs_medium_noise_015_m,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_medium_noise_05 = [
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m,
                "sigma_n": fhd_runs_medium_noise_05_m,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_medium_noise_1 = [
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m,
                "sigma_n": fhd_runs_medium_noise_1_m,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_small_noise_01 = [
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m / 10,
                "sigma_n": fhd_runs_medium_noise_01_m / 10,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_small_noise_015 = [
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m / 10,
                "sigma_n": fhd_runs_medium_noise_015_m / 10,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_small_noise_05 = [
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m / 10,
                "sigma_n": fhd_runs_medium_noise_05_m / 10,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_small_noise_1 = [
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m / 10,
                "sigma_n": fhd_runs_medium_noise_1_m / 10,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_large_noise_01 = [
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_01_m * 2,
                "sigma_n": fhd_runs_medium_noise_01_m * 2,
                "sigma_m": fhd_runs_medium_noise_01_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_large_noise_015 = [
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_015_m * 2,
                "sigma_n": fhd_runs_medium_noise_015_m * 2,
                "sigma_m": fhd_runs_medium_noise_015_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_large_noise_05 = [
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_05_m * 2,
                "sigma_n": fhd_runs_medium_noise_05_m * 2,
                "sigma_m": fhd_runs_medium_noise_05_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

fhd_runs_large_noise_1 = [
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 0.8,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 1.2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 2,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 5,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 10,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 50,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 100,
            },
            {
                "sigma_t": fhd_runs_medium_noise_1_m * 2,
                "sigma_n": fhd_runs_medium_noise_1_m * 2,
                "sigma_m": fhd_runs_medium_noise_1_m,
                "thermal_noise_realizations": max_realizations,
                "model_error_realizations": 0,
                "weighting_function": "constant_weights",
                "scaling_factor_cost": 200,
            },
        ]

def generate_files():
    cwd = os.getcwd()
    # with open(f'{cwd}/calico/data/sigma_combos_many_realizations.hkl', 'wb') as file:
    hkl.dump(many_sigma_combos, f'{cwd}/calico/data/sigma_combos_many_realizations.hkl', compression='gzip')
    # with open(f'{cwd}/calico/data/baseline_dependence_runs_large_noise.hkl', 'wb') as file:
    #     hkl.dump(baseline_dependence_runs_large_noise, file, compression='gzip')
    # with open(f'{cwd}/calico/data/baseline_dependence_runs_small_noise.hkl', 'wb') as file:
    #     hkl.dump(baseline_dependence_runs_small_noise, file, compression='gzip')
    # with open(f'{cwd}/calico/data/add_gaussian_error_large_noise.hkl', 'wb') as file:
    #     hkl.dump(add_gaussian_error_large_noise, file, compression='gzip')
    # with open(f'{cwd}/calico/data/add_gaussian_error_medium_noise.hkl', 'wb') as file:
    #     hkl.dump(add_gaussian_error_medium_noise, file, compression='gzip')
    # with open(f'{cwd}/calico/data/add_gaussian_error_small_noise.hkl', 'wb') as file:
    #     hkl.dump(add_gaussian_error_small_noise, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_medium_noise_01.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_medium_noise_01, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_medium_noise_015.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_medium_noise_015, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_medium_noise_05.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_medium_noise_05, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_medium_noise_1.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_medium_noise_1, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_small_noise_01.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_small_noise_01, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_small_noise_015.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_small_noise_015, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_small_noise_05.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_small_noise_05, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_small_noise_1.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_small_noise_1, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_large_noise_01.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_large_noise_01, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_large_noise_015.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_large_noise_015, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_large_noise_05.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_large_noise_05, file, compression='gzip')
    # with open(f'{cwd}/calico/data/fhd_runs_large_noise_1.hkl', 'wb') as file:
    #     hkl.dump(fhd_runs_large_noise_1, file, compression='gzip')

# Programmatically generate a custom file for a range of
# scaling factors passed by the user; the function using
# the scale factor assumes the weights of the form 1/sigma^2 
# so this function assumes the scale factors are w.r.t sigma
# itself and so must be converted accordingly.
def generate_custom_file(
    filename : str,
    scaling_factors : list,
    sigma_t : float = fhd_runs_medium_noise_015_m / 10,
    sigma_n : float = fhd_runs_medium_noise_015_m / 10,
    sigma_m : float = fhd_runs_medium_noise_015_m,
    sigma_e : float = fhd_runs_medium_noise_015_m,
    thermal_realizations : int = max_realizations,
    model_realizations : int = 0,
    weighting_function : str = "constant_weights",
    scaling_factor_sim : int = 1,
) -> None:
    custom_file = []
    for scaling_factor in scaling_factors:
        scaling_factor = 1 / scaling_factor**2
        custom_file.append(
            {
                "sigma_t": sigma_t,
                "sigma_n": sigma_n,
                "sigma_m": sigma_m,
                "sigma_e": sigma_e,
                "thermal_noise_realizations": thermal_realizations,
                "model_error_realizations": model_realizations,
                "weighting_function": weighting_function,
                "scaling_factor_cost": scaling_factor,
                "scaling_factor_sim": scaling_factor_sim,
            },
        )
    cwd = os.getcwd()
    with open(f'{cwd}/calico/data/{filename}_run_params.hkl', 'wb') as file:
        hkl.dump(custom_file, file, compression='gzip')